import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    anonymousId: v.optional(v.string()),
    canClaimDiamond: v.optional(v.boolean()),
    clerkId: v.optional(v.string()),
    credits: v.number(),
    diamondBalance: v.optional(v.number()),
    diamondSources: v.optional(v.array(v.string())),
    eliteProUntil: v.optional(v.number()),
    email: v.optional(v.string()),
    firstDiamondRatingPromptedAt: v.optional(v.number()),
    firstEntryRewardDismissedAt: v.optional(v.number()),
    generationCount: v.optional(v.number()),
    imageGenerationCount: v.optional(v.number()),
    imageLimit: v.optional(v.number()),
    // Older production rows may contain null while a user has never claimed.
    // Keep this optional so deployment can validate existing data safely.
    lastClaimAt: v.optional(v.number()),
    lastClaimDate: v.optional(v.number()),
    lastLoginDate: v.optional(v.number()),
    lastResetDate: v.optional(v.number()),
    lastReviewPromptAt: v.optional(v.number()),
    lastRewardDate: v.optional(v.number()),
    name: v.optional(v.string()),
    nextDiamondClaimAt: v.optional(v.number()),
    notificationsDeclined: v.optional(v.boolean()),
    notificationsPermissionGrantedAt: v.optional(v.number()),
    notificationsPermissionRequestedAt: v.optional(v.number()),
    onboardingDiamondClaimedAt: v.optional(v.number()),
    plan: v.optional(v.string()),
    premiumCredits: v.optional(v.number()),
    proTipNotificationIndex: v.optional(v.number()),
    proTrialEndedPaywallPending: v.optional(v.boolean()),
    proTrialEndedPaywallShownAt: v.optional(v.number()),
    proTrialExpiresAt: v.number(),
    referralCode: v.optional(v.string()),
    referralCount: v.optional(v.number()),
    referralProCount: v.optional(v.number()),
    reviewPrompted: v.optional(v.boolean()),
    streakCount: v.optional(v.number()),
    subscriptionEnd: v.optional(v.number()),
    subscriptionEntitlement: v.optional(v.string()),
    subscriptionStartedAt: v.optional(v.number()),
    subscriptionType: v.optional(v.string()),
    subscriptionStatus: v.optional(v.union(
      v.literal("active"),
      v.literal("canceled"),
      v.literal("expired"),
      v.literal("payment_failed"),
      v.literal("pending"),
    )),
    welcomeDiamondGiven: v.optional(v.boolean()),
    whopCustomerId: v.optional(v.string()),
    whopSubscriptionId: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }).index("by_clerkId", ["clerkId"])
    .index("by_email", ["email"]),

  projects: defineTable({
    userId: v.string(),
    title: v.string(),
    roomType: v.string(),
    style: v.string(),
    beforeImageUrl: v.optional(v.string()),
    afterImageUrl: v.optional(v.string()),
    prompt: v.optional(v.string()),
    budget: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_userId", ["userId"]),

  generations: defineTable({
    userId: v.string(),
    projectId: v.optional(v.string()),
    toolType: v.string(),
    creditsUsed: v.number(),
    inputImageUrl: v.optional(v.string()),
    outputImageUrl: v.optional(v.string()),
    prompt: v.optional(v.string()),
    status: v.union(v.literal("pending"), v.literal("processing"), v.literal("completed"), v.literal("failed")),
    createdAt: v.number(),
  }).index("by_userId", ["userId"])
    .index("by_status", ["status"]),

  uploads: defineTable({
    userId: v.string(),
    storageId: v.string(),
    fileName: v.string(),
    contentType: v.string(),
    fileSize: v.number(),
    createdAt: v.number(),
  }).index("by_userId", ["userId"]),
});
