import Image from "next/image";
import Link from "next/link";
import { SiteShell } from "@/components/layout/SiteShell";
import { DesignTool } from "@/components/tools/DesignTool";
import type { ToolConfig } from "@/lib/tool-data";

export function ToolLandingPage({ config }: { config: ToolConfig }) {
  return <SiteShell workspace><div className="create-main layout-initial"><section><div className="hero-mobile-banner mobile-only"><div className="hero-stat-badge hero-stat-badge-dark">{config.label}</div><div className="hero-mobile-title"><span className="hero-mobile-title-line1">{config.title}</span><span className="hero-mobile-title-line2">shaped around your space</span></div><p className="hero-supporting-copy">{config.description}</p><a href="#try-it-now" className="hero-start-btn">Start now →</a></div><div className="hero-split-layout desktop-only"><div className="hero-split-left"><div className="hero-stat-badge hero-stat-badge-dark">{config.label}</div><div className="hero-split-title"><div className="hero-split-title-line1">{config.title}</div><div className="hero-split-title-line2">shaped around your space</div></div><p className="hero-supporting-copy">{config.description}</p><a href="#try-it-now" className="hero-start-btn">Start now →</a></div><div className="hero-split-right"><div className="hero-desktop-slideshow"><Image src={config.hero} alt={`${config.title} example`} fill sizes="50vw" priority className="hero-desktop-slide active" /></div></div></div></section><DesignTool config={config} /><section className="id-challenge-card"><div className="id-challenge-header"><div><span className="workspace-eyebrow">THE PURPOSE</span><h2 className="id-challenge-heading">See the direction before making permanent decisions</h2></div><p className="id-challenge-intro">A photograph alone cannot show how a different style, finish, or layout will feel. Housora creates a visual concept grounded in your image.</p></div></section><section className="id-bottom-cta"><h2>Ready to explore your space?</h2><p>Start with your own photo and keep the concepts that fit.</p><div className="id-bottom-cta-links"><Link href="/sign-up?redirect=/design" className="id-bottom-cta-primary">Try Housora Free</Link><Link href="/examples" className="id-bottom-cta-secondary">Browse examples</Link></div></section></div></SiteShell>;
}
