export type ToolConfig = { title: string; label: string; description: string; hero: string; prompt: string };

export const toolConfigs: Record<string, ToolConfig> = {
  "interior-design": { title: "AI Interior Design", label: "AI Interior Design Tool", description: "Redesign any room from your own photo while keeping the original space as your reference.", hero: "/static/images/interior-after.jpg", prompt: "Describe the room, style, palette, and details you want to explore." },
  "layout-boost": { title: "AI Layout Boost", label: "AI Layout Tool", description: "Explore a clearer furniture arrangement and improve how your room flows.", hero: "/static/images/layout-after.jpg", prompt: "Describe what should feel easier or work better in the layout." },
  "exterior-design": { title: "AI Exterior Design", label: "AI Exterior Design Tool", description: "Explore finishes, colors, and architectural directions on your own property photo.", hero: "/static/images/exterior-after.jpg", prompt: "Describe the exterior style, materials, and colors you prefer." },
  "garden-design": { title: "AI Garden Design", label: "AI Garden Design Tool", description: "Visualize a new landscape direction grounded in your existing outdoor space.", hero: "/static/images/garden-after.jpg", prompt: "Describe the planting, surfaces, mood, and features you want." },
  "floor-restyle": { title: "AI Floor Restyle", label: "AI Flooring Tool", description: "Compare flooring materials and tones before making a permanent choice.", hero: "/static/images/floor-restyle-after.jpg", prompt: "Describe your preferred flooring material, color, and finish." },
  "wall-texture": { title: "AI Walls Texture", label: "AI Wall Finish Tool", description: "Explore paint, plaster, paneling, and wall texture ideas on your own room.", hero: "/static/images/walls-texture-after.jpg", prompt: "Describe the wall finish, tone, and level of texture." },
  "ai-stairs-design": { title: "AI Stairs Design", label: "AI Stairs Tool", description: "Explore staircase shapes, finishes, rails, and surrounding details.", hero: "/static/images/stairs-after.jpg", prompt: "Describe the staircase style, material, and railing." },
  "ai-doors-design": { title: "AI Doors Design", label: "AI Doors Tool", description: "Compare door styles and finishes in the context of your own space.", hero: "/static/images/door-modern-flush.jpg", prompt: "Describe the door style, material, color, and hardware." },
  "ai-windows-design": { title: "AI Windows Design", label: "AI Windows Tool", description: "Explore frame styles, proportions, and finishes on your property.", hero: "/static/images/windows-before.jpg", prompt: "Describe the window style, frame finish, and proportions." },
  "ai-kitchen-design": { title: "AI Kitchen Design", label: "AI Kitchen Tool", description: "Explore cabinetry, surfaces, colors, and layouts from a kitchen photo.", hero: "/static/images/kitchen-after.jpg", prompt: "Describe your preferred cabinets, worktops, palette, and layout." },
  "ai-bathroom-design": { title: "AI Bathroom Design", label: "AI Bathroom Tool", description: "Explore bathroom finishes, fixtures, storage, and atmosphere.", hero: "/static/images/bathroom-after.jpg", prompt: "Describe your preferred tiles, fixtures, storage, and palette." },
  "video-walkthrough": { title: "AI Video Walkthrough", label: "AI Walkthrough Tool", description: "Turn a finished room concept into a short visual walkthrough.", hero: "/static/images/hero-after.jpg", prompt: "Describe the camera movement and atmosphere." },
  "floorplan-to-3d": { title: "AI Floorplan to 3D", label: "Floorplan Visualization Tool", description: "Turn a clear floorplan into an easier-to-understand spatial concept.", hero: "/static/images/floorplan-after.jpg", prompt: "Describe the desired style and any room-specific priorities." },
  "photo-to-render": { title: "AI Photo to Render", label: "Architectural Render Tool", description: "Transform a reference photo into a polished architectural visualization.", hero: "/static/images/s-photo-render.jpg", prompt: "Describe the render style, lighting, materials, and mood." },
  "reference-style": { title: "Reference Style", label: "Reference-Guided Design Tool", description: "Use a visual reference to guide the direction applied to your own room.", hero: "/static/images/s-warm-render.jpg", prompt: "Describe which qualities from the reference should guide the result." },
};
