import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";
export const metadata: Metadata = { title: "Cookie & Storage Policy", robots: { index: false } };
const sections = [
  { heading: "Necessary storage", paragraphs: ["Necessary storage remains available when you choose Necessary only because it supports authentication, security, core product requests, and remembering your privacy choice."], items: ["housora-consent-v3 (localStorage): stores the analytics choice, policy version, date, and six-month expiry.", "housora_current_project (localStorage): remembers the locally selected project so the requested workspace flow can continue.", "Clerk cookies and storage, including names such as __session, __client, and __client_uat: maintain, refresh, and synchronize secure authentication sessions.", "Cloudflare security and delivery processing: protects and serves the website; exact security cookies depend on active Cloudflare features."] },
  { heading: "Optional analytics", paragraphs: ["The PostHog JavaScript SDK is downloaded and initialized only after analytics consent. It sends explicit page-view and product events, a random analytics identifier, and—after sign-in—the Clerk user ID with a plan property. PostHog may add standard SDK context such as browser, operating system, device class, referrer, locale, screen size, and network-derived IP handling according to your PostHog project settings."], items: ["Disabled: session recording, click/form autocapture, dead-click capture, heatmaps, performance capture, surveys, and automatic exception capture.", "Excluded intentionally: uploaded images, prompt or form text, email, name, payment-card data, and URL query strings."] },
  { heading: "Your choices", paragraphs: ["Necessary only keeps necessary services active and leaves PostHog disabled. Accept all additionally enables the disclosed optional analytics. Use Cookie settings in the footer to change or withdraw your choice at any time."] },
];
export default function CookiesPage() { return <LegalPage title="Cookie & Storage Policy" sections={sections} />; }
