import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/components/layout/SiteShell";

const competitors: Record<string, string> = { "housora-vs-reimaginehome": "REimagineHome", "housora-vs-homedesigns": "HomeDesignsAI", "housora-vs-mnml": "mnml.ai", "housora-vs-homestyler": "Homestyler", "housora-vs-planner5d": "Planner 5D" };
export function generateStaticParams() { return Object.keys(competitors).map((competitor) => ({ competitor })); }
export async function generateMetadata({ params }: { params: Promise<{ competitor: string }> }): Promise<Metadata> { const { competitor } = await params; const name = competitors[competitor]; return name ? { title: `Housora vs ${name}`, description: `A practical comparison of Housora and ${name}.` } : {}; }
export default async function ComparisonPage({ params }: { params: Promise<{ competitor: string }> }) { const { competitor } = await params; const name = competitors[competitor]; if (!name) notFound(); const rows = [["Photo-based redesign", "Focused", "Available"], ["Specialized room and exterior tools", "Included", "Varies"], ["Before/after decision support", "Central", "Varies"], ["Private project workspace", "Included", "Check current plan"], ["Clear consent controls", "Included", "Check current policy"]]; return <SiteShell><section className="compare-hero"><div className="compare-hero-inner"><span className="section-eyebrow">PRODUCT COMPARISON</span><h1>Housora vs {name}</h1><p>Compare the workflow and current product focus, then verify live pricing and capabilities directly before deciding.</p><Link href="/sign-up?redirect=/app/home" className="btn-primary btn-large">TRY HOUSORA</Link></div></section><section className="comparison-table-section"><div className="comparison-table"><div className="comparison-row comparison-header"><strong>Capability</strong><strong>Housora</strong><strong>{name}</strong></div>{rows.map(([capability, housora, other]) => <div className="comparison-row" key={capability}><span>{capability}</span><span>{housora}</span><span>{other}</span></div>)}</div></section><section className="compare-why"><h2>Why people may choose Housora</h2><p>Housora keeps the workflow centered on your own photo and on comparing clear visual directions across focused tools. The right choice still depends on the output, controls, price, and privacy terms that matter to you.</p></section></SiteShell>; }
